version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: aspirina765
#      ME_CONFIG_BASICAUTH_PASSWORD: aspirina765Express2023!
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: aspirina765Express2023!
    links:
      - mongo

  mongo:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: aspirina7652023!
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  web-scrapping-server:
    container_name: message-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: loterias-api:0.0.1-SNAPSHOT
    depends_on:
      - mongo

  jupyterlab:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes

    ports:
      - 8888:8888
    volumes:
      - ./shared-workspace:/opt/workspace

  spark-master:
    image: bde2020/spark-master:latest #3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - 8090:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - mongo

  spark-worker-1:
    image: bde2020/spark-worker:latest #3.2.0-hadoop3.2
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8080:8081
    volumes:
      - ./shared-workspaceshared-workspace:/opt/workspace
    depends_on:
      - spark-master
      - mongo


#  spark-worker-2:
#    image: bde2020/spark-worker:latest #3.2.0-hadoop3.2
#    container_name: spark-worker-2
#    environment:
#      - SPARK_WORKER_CORES=4
#      - SPARK_WORKER_MEMORY=4g
#      - SPARK_MASTER=spark://spark-master:7077
#    ports:
#      - 8082:8081
#    volumes:
#      - ./shared-workspaceshared-workspace:/opt/workspace
#    depends_on:
#      - spark-master
#      - mongo









