version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

#  web-scrapping-server:
#    container_name: message-server
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    image: loterias-api:0.0.1-SNAPSHOT
#    depends_on:
#      - mongo

