version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: aspirina765
#      ME_CONFIG_BASICAUTH_PASSWORD: aspirina765Express2023!
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: aspirina765Express2023!
    links:
      - mongo

  mongo:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: aspirina7652023!
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

